version: '3.8'

services:
  recipegenerator:
    image: oracolo/recipegenerator
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.80'
          memory: '500M'
        reservations:
          memory: '200M'
    ports:
      - "8085:8080"
    environment:
      - MAX_INGREDIENTS_PER_RECIPE=20
      - IMAGE_MAX_SIZE=5242880
      - MYSQL_HOST=mysql
      - MYSQL_USER=recipeuser
      - MYSQL_PASSWORD=recipeuser
      - MYSQL_PORT=3306
      - MYSQL_DB=recipedb
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - recipe_network
  mysql:
    image: mysql
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '800M'
        reservations:
          memory: '300M'
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=changeit
      - MYSQL_USER=recipeuser
      - MYSQL_PASSWORD=recipeuser
      - MYSQL_DATABASE=recipedb
    volumes:
      - recipegendata:/var/lib/mysql
    networks:
      - recipe_network
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=changeit --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 20s
      retries: 20
networks:
  recipe_network:
volumes:
  recipegendata: